# Generated by Django 2.0.6 on 2018-06-13 01:31

from django.db import migrations, models
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='文章标题')),
                ('summary', models.CharField(max_length=400, verbose_name='文章摘要')),
                ('body', models.FileField(upload_to='HTML/%Y/%m/%d')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('cover', models.TextField(default='http://p2p0dadp7.bkt.clouddn.com/Nighthawks.jpg', verbose_name='封面图片')),
                ('type', models.CharField(choices=[('TEXT', '文字'), ('PIC', '图片')], default='TEXT', max_length=20, verbose_name='展示类型')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='文章标签')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='消息内容')),
                ('publish_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
        ),
    ]
